### ISSUE TITLE
Array if integers with pllua-ng

### ISSUE THREAD

**Issue by intc** [pllua/pllua#4]
Hi!

I'm experimenting with REL_2_0_4 built with luajit-5.1. Hello example form https://pllua.github.io/pllua-ng/ works fine.

But no success with array_sum example:
```
create function array_sum(a integer[]) returns integer language pllua
as $$
  local total = 0
  for k,v in pairs(a) do
    total = total + v
  end
  return total
$$;
```
Here's what I tried: `select array_sum(array[1,2,3]);`
```
ERROR:  pllua: [string "array_sum"]:3: bad argument #1 to 'pairs' (table expected, got userdata)
```
`select array_sum(1|2|3);` didn't work either. What I'm doing wrong?

**Comment by RhodiumToad** [comment]
Did you build your luajit with the LUAJIT_ENABLE_LUA52COMPAT option? Without that, many features will not work.

**Comment by intc** [comment]
No I didn't.

I'm using Gentoo so added USE flag _lua52compat_ for **dev-lang/luajit**. Now it works as expected.

Thank you for your prompt response.

And thank you for the great software!
